# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20180122_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
