# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20180129_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name_plural': 'Ads'},
        ),
    ]
