# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-29 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
