# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
