# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-30 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20190130_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ('-is_vip', '-created'), 'verbose_name_plural': 'Ads'},
        ),
    ]
