# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ad_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
