# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedad',
            unique_together=set([('ad', 'user')]),
        ),
    ]
