# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 20:02
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20180424_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name_en', unique=True),
        ),
    ]
